# =============================================================================
# Shelzy's Designs - Daily Site Health Check
# =============================================================================
# Runs daily to verify site availability and performance
# Sends Slack/email notification if issues detected
# =============================================================================

name: Daily Site Health Check

on:
  schedule:
    # Run at 9 AM EST (2 PM UTC) every day
    - cron: '0 14 * * *'
  workflow_dispatch:  # Allow manual trigger

env:
  SITE_URL: https://shelzysdesigns.com
  PERFORMANCE_THRESHOLD: 70  # Lighthouse score threshold

jobs:
  availability-check:
    name: Check Site Availability
    runs-on: ubuntu-latest

    steps:
      - name: Check Homepage
        id: homepage
        run: |
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" ${{ env.SITE_URL }})
          echo "status=$HTTP_CODE" >> $GITHUB_OUTPUT
          if [ "$HTTP_CODE" != "200" ]; then
            echo "::error::Homepage returned HTTP $HTTP_CODE"
            exit 1
          fi
          echo "Homepage OK: HTTP $HTTP_CODE"

      - name: Check Collections Page
        id: collections
        run: |
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" ${{ env.SITE_URL }}/collections/all)
          echo "status=$HTTP_CODE" >> $GITHUB_OUTPUT
          if [ "$HTTP_CODE" != "200" ]; then
            echo "::warning::Collections page returned HTTP $HTTP_CODE"
          fi
          echo "Collections: HTTP $HTTP_CODE"

      - name: Check Cart Page
        id: cart
        run: |
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" ${{ env.SITE_URL }}/cart)
          echo "status=$HTTP_CODE" >> $GITHUB_OUTPUT
          if [ "$HTTP_CODE" != "200" ]; then
            echo "::warning::Cart page returned HTTP $HTTP_CODE"
          fi
          echo "Cart: HTTP $HTTP_CODE"

      - name: Check Contact Page
        id: contact
        run: |
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" ${{ env.SITE_URL }}/pages/contact)
          echo "status=$HTTP_CODE" >> $GITHUB_OUTPUT
          echo "Contact: HTTP $HTTP_CODE"

      - name: Check Response Time
        id: response_time
        run: |
          RESPONSE_TIME=$(curl -s -o /dev/null -w "%{time_total}" ${{ env.SITE_URL }})
          echo "time=$RESPONSE_TIME" >> $GITHUB_OUTPUT
          echo "Response time: ${RESPONSE_TIME}s"

          # Warn if response time > 3 seconds
          if (( $(echo "$RESPONSE_TIME > 3" | bc -l) )); then
            echo "::warning::Response time is slow: ${RESPONSE_TIME}s"
          fi

  lighthouse-audit:
    name: Run Lighthouse Audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Lighthouse
        id: lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            ${{ env.SITE_URL }}
            ${{ env.SITE_URL }}/collections/all
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Check Performance Score
        run: |
          # Parse Lighthouse results
          SCORE=$(echo '${{ steps.lighthouse.outputs.manifest }}' | jq -r '.[0].summary.performance * 100 | floor')
          echo "Performance Score: $SCORE"

          if [ "$SCORE" -lt "${{ env.PERFORMANCE_THRESHOLD }}" ]; then
            echo "::warning::Performance score ($SCORE) is below threshold (${{ env.PERFORMANCE_THRESHOLD }})"
          fi

  ssl-check:
    name: Check SSL Certificate
    runs-on: ubuntu-latest

    steps:
      - name: Check SSL Expiry
        run: |
          DOMAIN="shelzysdesigns.com"
          EXPIRY=$(echo | openssl s_client -servername $DOMAIN -connect $DOMAIN:443 2>/dev/null | openssl x509 -noout -enddate | cut -d= -f2)
          EXPIRY_EPOCH=$(date -d "$EXPIRY" +%s)
          NOW_EPOCH=$(date +%s)
          DAYS_LEFT=$(( ($EXPIRY_EPOCH - $NOW_EPOCH) / 86400 ))

          echo "SSL Certificate expires: $EXPIRY"
          echo "Days remaining: $DAYS_LEFT"

          if [ "$DAYS_LEFT" -lt 30 ]; then
            echo "::warning::SSL certificate expires in $DAYS_LEFT days!"
          fi

  notify-on-failure:
    name: Send Notification
    runs-on: ubuntu-latest
    needs: [availability-check, lighthouse-audit, ssl-check]
    if: failure()

    steps:
      - name: Send Slack Notification
        if: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"⚠️ Shelzy'\''s Designs Site Health Check Failed!\nCheck: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Site Health Check Failed - ' + new Date().toISOString().split('T')[0],
              body: 'The daily site health check has detected issues.\n\nCheck the [workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.',
              labels: ['bug', 'priority-high']
            })
